export {default as Jumbotron} from './jumbotron'
export {default as Footer} from './footer'
export {default as Accordion} from './accordion'
export {default as InputForm} from './inputform'
export {default as Plans} from './plans'
export {default as Card} from './card'