export { default as Jumbotron } from './jumbotron'
export { default as Footer } from './footer'
export { default as Accordion } from './accordion'
export { default as InputForm } from './inputform'
export { default as Plans } from './plans'
export { default as Card } from './card'
export { default as Header } from './header'
export { default as Nav } from './nav'
export { default as Form } from './form'
export {default as Profiles} from  './profiles'
export {default as Loading} from './loading'
export {default as List} from './list'
export {default as Player} from './player'
export {default as Banner} from './banner'
export {default as Recommend} from './recommend'
export {default as BrowseHeader} from './browseheader'